<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>schema</string>
    </array>
    <key>name</key>
    <string>SpatialOS Schema</string>
    <key>scopeName</key>
    <string>source.schema</string>
    <key>uuid</key>
    <string>8751c4b8-ddba-49e9-bc2b-692b27305ffc</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#package</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#import</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>name</key>
        <string>meta.type.type</string>
        <key>comment</key>
        <string>type definition</string>
        <key>begin</key>
        <string>(type)\s+(\w+)\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>meta.type.component</string>
        <key>comment</key>
        <string>component definition</string>
        <key>begin</key>
        <string>(component)\s+(\w+)\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#storage</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#id</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#command</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#event</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#field</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>meta.type.enum</string>
        <key>comment</key>
        <string>enum definition</string>
        <key>begin</key>
        <string>(enum)\s+(\w+)\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#enumField</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
        </array>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>command</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.keyword</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.data</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.keyword</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>storage.type.data</string>
          </dict>
        </dict>
        <key>comment</key>
        <string>command declaration</string>
        <key>match</key>
        <string>(command)\s+([\w\.]+)\s+([\w_]+)\s+(returns)\s+([\w\.]+)\s*\;</string>
        <key>name</key>
        <string>meta.component.body</string>
      </dict>
      <key>comment</key>
      <dict>
        <key>begin</key>
        <string>//</string>
        <key>comment</key>
        <string>a schema comment</string>
        <key>end</key>
        <string>$\n?</string>
        <key>name</key>
        <string>comment.line.double-slash</string>
      </dict>
      <key>event</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.data</string>
          </dict>
        </dict>
        <key>comment</key>
        <string>event declaration</string>
        <key>match</key>
        <string>(event)\s+([\w\.]+)\s+([\w_]+)\s*\;</string>
        <key>name</key>
        <string>meta.component.body</string>
      </dict>
      <key>enumField</key>
      <dict>
        <key>name</key>
        <string>meta.type.enumField</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.numeric</string>
              </dict>
            </dict>
            <key>match</key>
            <string>[\w_]+\s*(\=)\s*(\d+)\s*\;</string>
            <key>name</key>
            <string>meta.type.enumField</string>
          </dict>
        </array>
      </dict>
      <key>field</key>
      <dict>
        <key>comment</key>
        <string>field definition</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>constant.numeric</string>
              </dict>
            </dict>
            <key>match</key>
            <string>([\w\.]+)\s+([\w_]+)\s*(\=)\s*(\d+)\s*\;</string>
            <key>name</key>
            <string>meta.type.field</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>storage.type</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>keyword.operator</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>constant.numeric</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(map)\&lt;([\w\.]+)(\,)\s*([\w\.]+)\&gt;\s+([\w_]+)\s*(\=)\s*(\d+)\s*\;</string>
            <key>name</key>
            <string>meta.type.field</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.operator</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>constant.numeric</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(list)\&lt;([\w\.]+)\&gt;\s+([\w_]+)\s*(\=)\s*(\d+)\s*\;</string>
            <key>name</key>
            <string>meta.type.field</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.operator</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>constant.numeric</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(option)\&lt;([\w\.]+)\&gt;\s+([\w_]+)\s*(\=)\s*(\d+)\s*\;</string>
            <key>name</key>
            <string>meta.type.field</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.operator</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>constant.boolean</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(option)\s+([\w_]+)\s*(\=)\s*(true|false)\s*\;</string>
            <key>name</key>
            <string>meta.type.field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#primitive</string>
          </dict>
        </array>
      </dict>
      <key>id</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.numeric</string>
          </dict>
        </dict>
        <key>comment</key>
        <string>id declaration</string>
        <key>match</key>
        <string>(id)\s*(\=)\s*(\d+)\s*\;</string>
        <key>name</key>
        <string>meta.component.body</string>
      </dict>
      <key>import</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.import</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>support.class.import</string>
          </dict>
        </dict>
        <key>comment</key>
        <string>import company.package;</string>
        <key>match</key>
        <string>(import)\s+("[\w\/]+[a-zA-Z0-9_]+\.schema")\s*\;</string>
        <key>name</key>
        <string>meta.import</string>
      </dict>
      <key>package</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.package</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>support.other.package</string>
          </dict>
        </dict>
        <key>comment</key>
        <string>package company.package;</string>
        <key>match</key>
        <string>(package)\s+([\w\.]+)\s*\;</string>
        <key>name</key>
        <string>meta.package</string>
      </dict>
      <key>primitive</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.primitive</string>
          </dict>
        </dict>
        <key>comment</key>
        <string>built in data type</string>
        <key>match</key>
        <string>\b(bool|uint32|uint64|int32|int64|sint32|sint64|fixed32|fixed64|sfixed32|sfixed64|float|double|string|bytes|Coordinates|Vector3d|Vector3f|EntityId|EntityPosition|option|map)\b</string>
        <key>name</key>
        <string>meta.declaration.body</string>
      </dict>
      <key>constant</key>
      <dict>
        <key>name</key>
        <string>constant.boolean</string>
        <key>match</key>
        <string>(true|false)</string>
      </dict>
      <key>storage</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.data</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.data</string>
          </dict>
        </dict>
        <key>comment</key>
        <string>data declaration</string>
        <key>match</key>
        <string>(data)\s+([\w\.]+)\s*\;</string>
        <key>name</key>
        <string>meta.component.body</string>
      </dict>
    </dict>
  </dict>
</plist>