<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>schema</string>
	</array>
	<key>name</key>
	<string>SpatialOS Schema</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#package</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#import</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#enum-declaration</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#type-declaration</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#component-declaration</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.schema</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.schema</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.schema</string>
		</dict>
		<key>command</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.command.schema</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.member.schema</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.parenthesis.open.schema</string>
				</dict>
				<key>5</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.parenthesis.close.schema</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.schema</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(command)(?:\s+((?:\w+(?:\.\w+)*)(?:\&lt;[\w\s,\.]+\&gt;)?)(?:\s+(\w+)(?:\s*(?:(\()((?:\w+(?:\.\w+)*)(?:\&lt;[\w\s,\.]+\&gt;)?)(?:(\))\s*(\;)?)?)?)?)?)?</string>
		</dict>
		<key>command-legacy</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.command.schema</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.member.schema</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.other.command-returns.schema</string>
				</dict>
				<key>5</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.schema</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(command)(?:\s+((?:\w+(?:\.\w+)*)(?:\&lt;[\w\s,\.]+\&gt;)?)(?:\s+(\w+)(?:\s+(returns)(?:\s+((?:\w+(?:\.\w+)*)(?:\&lt;[\w\s,\.]+\&gt;)?)\s*(\;)?)?)?)?)?</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-comment</string>
				</dict>
			</array>
		</dict>
		<key>component-declaration</key>
		<dict>
			<key>begin</key>
			<string>(component)(?:\s+(\w+)\s*(\{)?)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.component.schema</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.component.schema</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.curlybrace.open.schema</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.curlybrace.close.schema</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.component</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#id</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#data</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#event</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#field</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.boolean.schema</string>
		</dict>
		<key>data</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.data.schema</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.schema</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(data)(?:\s+((?:\w+(?:\.\w+)*)(?:\&lt;[\w\s,\.]+\&gt;)?)\s*(\;)?)?</string>
			<key>name</key>
			<string>meta.component.body</string>
		</dict>
		<key>enum-declaration</key>
		<dict>
			<key>begin</key>
			<string>(enum)(\s+(\w+)\s*(\{)?)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.enum.schema</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.enum.schema</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.curlybrace.open.schema</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.curlybrace.close.schema</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.enum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#enum-member</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>enum-member</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.enum-member.schema</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.schema</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.schema</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.schema</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)\s*((\=)\s*((\d+)\s*(\;)?)?)?</string>
			<key>name</key>
			<string>meta.enum.member</string>
		</dict>
		<key>event</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.event.schema</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.member.schema</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.schema</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(event)(?:\s+((?:\w+(?:\.\w+)*)(?:\&lt;[\w\s,\.]+\&gt;)?)(?:\s+(\w+)\s*(\;)?)?)?</string>
		</dict>
		<key>field</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#transient-type</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.member.schema</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.schema</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.schema</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.schema</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((?:transient\s+)?(?:\w+(?:\.\w+)*)(?:\&lt;[\w\s,\.]+\&gt;)?)(?:\s+(\w+)(?:\s*(\=)(?:\s*(\d+)\s*(\;)?)?)?)?</string>
		</dict>
		<key>id</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.member.schema</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.schema</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.schema</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.schema</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(id)(?:\s*(\=)(?:\s*(\d+)\s*(\;)?)?)?</string>
		</dict>
		<key>import</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.import.schema</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.schema</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.schema</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(import)(\s+("[\w\.\/-]*")\s*(;)?)?</string>
			<key>name</key>
			<string>meta.import</string>
		</dict>
		<key>line-comment</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.schema</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.schema</string>
		</dict>
		<key>option</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.option.schema</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.member.schema</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.schema</string>
				</dict>
				<key>4</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#constant</string>
						</dict>
					</array>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.schema</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(option)(?:\s+(\w+)(?:\s*(\=)(?:\s*(\w+)\s*(\;)?)?)?)?</string>
		</dict>
		<key>package</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.package.schema</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.package.schema</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.schema</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(package)(\s+([\w\.]+)\s*(;)?)?</string>
			<key>name</key>
			<string>meta.package</string>
		</dict>
		<key>transient-type</key>
		<dict>
			<key>begin</key>
			<string>\b(transient)\s+(map|list|option)(&lt;)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.transient.schema</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.type.schema</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.typeparameters.begin.schema</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.typeparameters.end.schema</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.comma.schema</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*(,)\s*</string>
				</dict>
			</array>
		</dict>
		<key>type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-generic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-builtin</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-custom</string>
				</dict>
			</array>
		</dict>
		<key>type-builtin</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.type.schema</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(bool|uint32|uint64|int32|int64|sint32|sint64|fixed32|fixed64|sfixed32|sfixed64|float|double|string|bytes|Coordinates|Vector3d|Vector3f|EntityId|EntityPosition)\b</string>
		</dict>
		<key>type-custom</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.schema</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(\w+(?:\.\w+)*)\b</string>
		</dict>
		<key>type-declaration</key>
		<dict>
			<key>begin</key>
			<string>(type)(\s+(\w+)\s*(\{)?)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.type.schema</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.type.schema</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.curlybrace.open.schema</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.curlybrace.close.schema</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.type</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#field</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>type-generic</key>
		<dict>
			<key>begin</key>
			<string>\b(map|list|option)(&lt;)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.type.schema</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.typeparameters.begin.schema</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.typeparameters.end.schema</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.comma.schema</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*(,)\s*</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.schema</string>
	<key>uuid</key>
	<string>8751c4b8-ddba-49e9-bc2b-692b27305ffc</string>
</dict>
</plist>
